### ISSUE TITLE
请问WDA建立session后能否跨应用操作

### ISSUE THREAD

**Issue by czwtest** [openatx/wdaproxy#16]
我这边测试发现wda建立session以后，打开其他应用获取的size为0，做点击操作不会生效，是否有方式实现跨应用操作

**Comment by codeskyblue** [comment]
应该不影响的，wda最新了吗

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codeskyblue** [comment]
session主要是用来判断其对应的进程是否存活

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by czwtest** [comment]
> session主要是用来判断其对应的进程是否存活
> Sent with GitHawk

当前session不关闭，切到桌面点击打开其他app以后，在新打开的app里面不能再做任何操作，wda都是最新的

**Comment by czwtest** [comment]
> session主要是用来判断其对应的进程是否存活
> Sent with GitHawk

我看你们的项目好像都是启动session打开设置，然后再操作其他app，好像没有这类限制，想确认是否是我自己操作问题

**Comment by codeskyblue** [comment]
操作没问题，这边测试过没这个限制。源码也没有限制

**Comment by czwtest** [comment]
> 操作没问题，这边测试过没这个限制。源码也没有限制

谢谢，我这边再试试看
