### ISSUE TITLE
不太懂这个feature

### ISSUE THREAD

**Issue by youran1024** [openatx/wdaproxy#18]
请问为什么要监听0.0.0.0 这个地址那？
 Launch iproxy when start. Listen on 0.0.0.0 instead of localhost

**Comment by codeskyblue** [comment]
这样其他机器就能请求过来啦

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by youran1024** [comment]
> 这样其他机器就能请求过来啦
> 
> Sent with [GitHawk](http://githawk.com)
多谢， 还有一个问题
端口转发也是这样的吗？ 不太明白为什么要监听一个端口再转发到另一个端口上

**Comment by codeskyblue** [comment]
因为iproxy不支持监听0.0.0.0，只能在中转一层了。ok的话就把issue关掉吧

**Comment by youran1024** [comment]
好的啊， 多谢啦
