### ISSUE TITLE
Need more info on wdaproxy

### ISSUE THREAD

**Issue by vathsalahn** [openatx/wdaproxy#2]
Is this library removing the dependency on iproxy ??.Need more info on what wdaproxy does??

**Comment by codeskyblue** [comment]
you want to know what? wdaproxy need iproxy

**Comment by vathsalahn** [comment]
Is WDA proxy related to Facebook webdriverAgent ?? Can I change the port of Facebook WDA using wdaproxy?? ..What actually is wdaproxy and its functionality??

**Comment by codeskyblue** [comment]
yes related to wda facebook, but the main function is simple, launch iproxy and proxy iproxy listen address to public, so I can call wda in windows

**Comment by codeskyblue** [comment]
Is the Readme not  very clear?

**Comment by codeskyblue** [comment]
reopen if you got more questions
