### ISSUE TITLE
mac 通过USB插上手机启动wdaproxy命令，报错main.go:215: exit status 234

### ISSUE THREAD

**Issue by Maxxxx24** [openatx/wdaproxy#20]
$wdaproxy -u aa225d9f679ccfb29df67ad5d85f0fe935b2xxxx -p 8200
2020/06/18 12:57:20 main.go:131: freeport 53222
2020/06/18 12:57:20 main.go:134: launch tcp-proxy, listen on 8200
2020/06/18 12:57:20 main.go:214: Open webbrower with http://10.xx.12.xxx:8200
2020/06/18 12:57:20 main.go:141: launch iproxy (udid: "aa225d9f679ccfb29df67ad5d85f0fe935b23903")
2020/06/18 12:57:20 main.go:215: exit status 234

**Comment by Maxxxx24** [comment]
修改源码后已解决

**Comment by cheliosooo** [comment]
I am also getting this issue now every time, even though it was working fine just yesterday. Do you know what the underlying problem is? What did you do to fix it?

我也每次都收到此问题，即使昨天才运行良好。您知道潜在的问题是什么吗？您做了什么修复？

**Comment by AngryBaby** [comment]
> 修改源码后已解决

@Maxdong24 你是修改了哪些代码呢

**Comment by yanglovecode** [comment]
> 修改源码后已解决

求修改后的源码

**Comment by yanglovecode** [comment]
@Maxdong24
